Config = Config or {}

Config.RepeatTimeout = 2500
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa fa-phone-alt",
        tooltipText = "الهاتف",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa fa-cog",
        tooltipText = "الإعدادات",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "الشرطة",
        job = "police",
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["store"] = {
        app = "store",
        color = "#27ae60",
        icon = "fas fa-cart-arrow-down",
        tooltipText = "متجر التطبيقات",
        tooltipPos = "right",
        style = "padding-right: .3vh; font-size: 2.2vh";
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
        ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        tooltipText = "تويتر",
        tooltipPos = "bottom",
        style = "",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
        password = false,
        creator = "KNFH Store",
        title = "تويتر",
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#25d366",
        icon = "fab fa-whatsapp",
        tooltipText = "واتس اب",
        tooltipPos = "bottom",
        style = "",
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
        password = false,
        creator = "KNFH Store",
        title = "واتس اب",
    },
	["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "fas fa-warehouse",
		tooltipPos = "bottom",
        tooltipText = "الكراج",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "الكراج"
    },
    ["mail"] = {
        app = "mail",
        color = "#ff002f",
        icon = "fas fa-envelope",
        tooltipText = "البريد",
		tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "البريد"
    },
    ["advert"] = {
        app = "advert",
        color = "#ff8f1a",
        icon = "fas fa-ad",
		tooltipPos = "bottom",
        tooltipText = "الاْعلانات",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "الاْعلانات"
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        icon = "fas fa-university",
        tooltipText = "البنك",
		tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "البنك"
    },
    ["crypto"] = {
        app = "crypto",
        color = "#004682",
        icon = "fas fa-chart-pie",
        tooltipText = "البيتكوين",
		tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "البيتكوين"
    },
    ["racing"] = {
        app = "racing",
        color = "#353b48",
        icon = "fas fa-flag-checkered",
        tooltipText = "السباق",
		tooltipPos = "bottom",
        job = false,
        blockedjobs = {
            "police"
        },
        slot = 10,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "السباق"
    },
    ["houses"] = {
        app = "houses",
        color = "#27ae60",
        icon = "fas fa-home",
        tooltipText = "المنازل",
		tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "المنازل"
    },
	["lawyers"] = {
        app = "lawyers",
        color = "#353b48",
        icon = "fas fa-user-tie",
        tooltipText = "حقوق المواطن",
		tooltipPos = "bottom",
        --tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "حقوق المواطن"
    },
		["taxis"] = {
        app = "taxis",
        color = "#d1d100",
		icon = "fas fa-taxi",
        tooltipText = "تطبيق التاكسي",
		tooltipPos = "bottom",
       -- tooltipPos = "right",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "تاكسي الغزال"
    },
	["tows"] = {
        app = "tows",
        color = "#9800d4",
        icon = "fas fa-car-crash",
		tooltipPos = "bottom",
        tooltipText = "سطحة",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "سطحات دوت كوم"
    },
	["mechanic"] = {
        app = "mechs",
        color = "#F00F0F",
        icon = "fas fa-car-battery",
		tooltipPos = "bottom",
        tooltipText = "الميكانيكي",
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
		style = "",
		password = false,
        creator = "KNFH Store",
        title = "ميكانيكي"
    },
	
	
    -- ["trucker"] = {
    --     app = "trucker",
    --     color = "#cccc33",
    --     icon = "fas fa-truck-moving",
    --     tooltipText = "Dumbo",
    --     tooltipPos = "right",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 17,
    --     Alerts = 0,
    -- },
}
Config.MaxSlots = 20

Config.StoreApps = {

    },
}